version = 0.1
[default.deploy.parameters]
stack_name = "oppgave-1-2024"
resolve_s3 = true
s3_prefix = "oppgave-1-2024"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
